Coords const SelectActionState::RoomDescriptionCoords1(1, 5);
Coords const SelectActionState::RoomDescriptionCoords2(1, 8);
Coords const SelectActionState::FeedBackCoords(1, 11);
Coords const SelectActionState::RoomLabelCoords(20, 0);

Coords const SelectActionState::ContextAction1Coords(1, 14);
Coords const SelectActionState::ContextAction2Coords(1, 15);
Coords const SelectActionState::ContextAction3Coords(1, 16);
Coords const SelectActionState::BaseMenuCoords(1, 17);

static std::string const SelectActionState::BaseMenuString
(u8R"((w)   Gehe Forwärts
(a)   Nach links drehen
(d)   Nach rechts drehen
(e)   Untersuche
(i)   Inventar öffnen

(ESC) Spiel beenden)");


