Coords const SelectActionState::RoomDescriptionCoords1(0, 2);
Coords const SelectActionState::RoomDescriptionCoords2(0, 5);
Coords const SelectActionState::FeedBackCoords(0, 8);

Coords const SelectActionState::ContextAction1Coords(0, 13);
Coords const SelectActionState::ContextAction2Coords(0, 14);
Coords const SelectActionState::ContextAction3Coords(0, 15);
Coords const SelectActionState::BaseMenuCoords(0, 16);

std::string const SelectActionState::BaseMenuString
(u8R"((w)   Gehe Forwärts
(a)   Nach links drehen
(d)   Nach rechts drehen
(e)   Untersuche
(i)   Inventar öffnen
(c)   Kompass anzeigen

(ESC) Spiel beenden)");


